### ISSUE TITLE
Nybble Forth

### ISSUE THREAD

**Issue by larsbrinkhoff** [The-Blue-Wizard/Miscellany#2]
Hello,

It appears I got the same idea you had some time ago, and even named it almost the same:

http://github.com/larsbrinkhoff/nybbleForth

**Comment by The-Blue-Wizard** [comment]
I am baffled by your comment....exactly what idea(s) did I have? And how is it connected to my Miscellany, which is a collection of unrelated little stuff? Besides, you might want to give @sam-falvo some heads up regarding your nybbleForth though! I'm sure he would be quite interested in your project/ideas!

**Comment by larsbrinkhoff** [comment]
It's on line 401 in this IRC log:  
http://forthworks.com/forth/irc-logs/05.07.02

It doesn't have anything to do with your Miscellany repository, sorry.  But there isn't a way to send a plain message to a GitHub user.

**Comment by The-Blue-Wizard** [comment]
Wow! I have totally forgotten about that...so long ago! I now feel old, ancient even! But I did think about the nybble based CPU, though IIRC I had not fully figured out a good approach at that time. Anyway, now there's a [Quark CPU](https://github.com/drom/quark), and Samuel Falvo has his own version as well. I nowadays have a different idea/design in my head...I haven't really worked on it though LOL! Too many other things calling my attention! 😁 By the way, I must say I am no hardware guy...purely software guy.

**Comment by larsbrinkhoff** [comment]
Thanks!  I'm taking a look at the Quark and the S16X4.

**Comment by sam-falvo** [comment]
Probably want to study the S16X4A, its successor.  It adds a small number of useful instructions making subroutine calls easier.

**Comment by The-Blue-Wizard** [comment]
Thanks for the discussion. I advise that in the future use my ["AMA"](https://github.com/The-Blue-Wizard/ama) repository to Ask Me Anything. I shall close this issue now. Thanks!
